services:
  - type: web
    name: sjogu-university
    runtime: image
    repo: https://github.com/stevrk/SJOGU2.git
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://sjogu-university.onrender.com
      - key: SESSION_DRIVER
        value: file
      - key: DB_CONNECTION
        value: sqlite